global:
  scrape_interval: 15s
remote_write:
  url: 'https://frontend.dev.weave.works/api/prom/push'
  basic_auth:
    password: bci9guhmdn55ierszy4maxpbxmdepmry
scrape_configs:
  - job_name: swarm-service-endpoints
    file_sd_configs:
      - files:
        - /etc/swarm-endpoints/swarm-endpoints.json
